<a href="https://colab.research.google.com/github/Omprakash143om/IRIS_FLOWER_PREDICTION_USING_CNN/blob/PROGRAMS/DEEPLEARNING_CNN_IRIS_FLOWER_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import seaborn as sns

In [ ]:
df=sns.load_dataset("iris")

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
dictionary={"setosa":0,"versicolor":1,"virginica":2}
df["species"]=df["species"].map(dictionary)

In [ ]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width  species
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

In [ ]:
x=df.drop("species",axis=1)

In [ ]:
import tensorflow as tf

In [ ]:
y=tf.keras.utils.to_categorical(df['species'])

In [ ]:
inputlayer=tf.keras.layers.Dense(units=4,input_dim=4)
hlayer1=tf.keras.layers.Dense(units=32)
hlayer2=tf.keras.layers.Dense(units=32)
hlayer3=tf.keras.layers.Dense(units=64)
hlayer4=tf.keras.layers.Dense(units=64)
hlayer5=tf.keras.layers.Dense(units=128)
hlayer6=tf.keras.layers.Dense(units=64)
outputlayer=tf.keras.layers.Dense(units=3,activation='softmax')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model=tf.keras.Sequential()
model.add(inputlayer)
model.add(hlayer1)
model.add(hlayer2)
model.add(hlayer3)
model.add(hlayer4)
model.add(hlayer5)
model.add(hlayer6)
model.add(outputlayer)

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(x,y,epochs=10)

Epoch 1/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9474 - loss: 0.1405
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9440 - loss: 0.1398
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9643 - loss: 0.1251
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9159 - loss: 0.1870
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9047 - loss: 0.2245
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9741 - loss: 0.0880
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9536 - loss: 0.1113
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9650 - loss: 0.0814
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9528 - loss: 0.0905
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9802 - loss: 0.0678

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
import numpy as np

model.predict(np.array([[5.1,3.5,1.4,0.2]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

array([[9.9962604e-01, 3.7393512e-04, 1.0213074e-15]], dtype=float32)

In [ ]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width  species
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

In [ ]:
model.predict(np.array([[5.9,3.0,5.1,1.8]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

array([[3.2537275e-07, 1.0732064e-01, 8.9267898e-01]], dtype=float32)